import type { Attendance } from "./types";

export const mockAttendance: Attendance[] = [
  {
    id: "1",
    companyId: "company-1",
    userId: "user-1",
    name: "John Doe",
    date: "2026-02-22",
    checkIn: "08:05",
    checkOut: "17:02",
    status: "Present",
  },
  {
    id: "2",
    companyId: "company-1",
    userId: "user-2",
    name: "Jane Smith",
    date: "2026-02-22",
    checkIn: "08:00",
    checkOut: "17:00",
    status: "Present",
  },
  {
    id: "3",
    companyId: "company-1",
    userId: "user-3",
    name: "Bob Wilson",
    date: "2026-02-22",
    checkIn: "08:15",
    checkOut: "17:10",
    status: "Late",
  },
  {
    id: "4",
    companyId: "company-1",
    userId: "user-4",
    name: "Alice Brown",
    date: "2026-02-22",
    checkIn: "07:55",
    checkOut: "17:05",
    status: "Present",
  },
  {
    id: "5",
    companyId: "company-1",
    userId: "user-5",
    name: "Charlie Davis",
    date: "2026-02-22",
    checkIn: "-",
    checkOut: "-",
    status: "Absent",
  },
];
