/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ScheduleRouteImport } from './routes/schedule'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LeaveRouteImport } from './routes/leave'
import { Route as CustomHolidaysRouteImport } from './routes/custom-holidays'
import { Route as CalendarRouteImport } from './routes/calendar'
import { Route as AttendanceRouteImport } from './routes/attendance'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ScheduleSalesRouteImport } from './routes/schedule.sales'
import { Route as ScheduleMyRouteImport } from './routes/schedule.my'

const ScheduleRoute = ScheduleRouteImport.update({
  id: '/schedule',
  path: '/schedule',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaveRoute = LeaveRouteImport.update({
  id: '/leave',
  path: '/leave',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomHolidaysRoute = CustomHolidaysRouteImport.update({
  id: '/custom-holidays',
  path: '/custom-holidays',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarRoute = CalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const AttendanceRoute = AttendanceRouteImport.update({
  id: '/attendance',
  path: '/attendance',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ScheduleSalesRoute = ScheduleSalesRouteImport.update({
  id: '/sales',
  path: '/sales',
  getParentRoute: () => ScheduleRoute,
} as any)
const ScheduleMyRoute = ScheduleMyRouteImport.update({
  id: '/my',
  path: '/my',
  getParentRoute: () => ScheduleRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/attendance': typeof AttendanceRoute
  '/calendar': typeof CalendarRoute
  '/custom-holidays': typeof CustomHolidaysRoute
  '/leave': typeof LeaveRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/reports': typeof ReportsRoute
  '/schedule': typeof ScheduleRouteWithChildren
  '/schedule/my': typeof ScheduleMyRoute
  '/schedule/sales': typeof ScheduleSalesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/attendance': typeof AttendanceRoute
  '/calendar': typeof CalendarRoute
  '/custom-holidays': typeof CustomHolidaysRoute
  '/leave': typeof LeaveRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/reports': typeof ReportsRoute
  '/schedule': typeof ScheduleRouteWithChildren
  '/schedule/my': typeof ScheduleMyRoute
  '/schedule/sales': typeof ScheduleSalesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/attendance': typeof AttendanceRoute
  '/calendar': typeof CalendarRoute
  '/custom-holidays': typeof CustomHolidaysRoute
  '/leave': typeof LeaveRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/reports': typeof ReportsRoute
  '/schedule': typeof ScheduleRouteWithChildren
  '/schedule/my': typeof ScheduleMyRoute
  '/schedule/sales': typeof ScheduleSalesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/attendance'
    | '/calendar'
    | '/custom-holidays'
    | '/leave'
    | '/login'
    | '/register'
    | '/reports'
    | '/schedule'
    | '/schedule/my'
    | '/schedule/sales'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/attendance'
    | '/calendar'
    | '/custom-holidays'
    | '/leave'
    | '/login'
    | '/register'
    | '/reports'
    | '/schedule'
    | '/schedule/my'
    | '/schedule/sales'
  id:
    | '__root__'
    | '/'
    | '/attendance'
    | '/calendar'
    | '/custom-holidays'
    | '/leave'
    | '/login'
    | '/register'
    | '/reports'
    | '/schedule'
    | '/schedule/my'
    | '/schedule/sales'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AttendanceRoute: typeof AttendanceRoute
  CalendarRoute: typeof CalendarRoute
  CustomHolidaysRoute: typeof CustomHolidaysRoute
  LeaveRoute: typeof LeaveRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  ReportsRoute: typeof ReportsRoute
  ScheduleRoute: typeof ScheduleRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/schedule': {
      id: '/schedule'
      path: '/schedule'
      fullPath: '/schedule'
      preLoaderRoute: typeof ScheduleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leave': {
      id: '/leave'
      path: '/leave'
      fullPath: '/leave'
      preLoaderRoute: typeof LeaveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/custom-holidays': {
      id: '/custom-holidays'
      path: '/custom-holidays'
      fullPath: '/custom-holidays'
      preLoaderRoute: typeof CustomHolidaysRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendar': {
      id: '/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof CalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/attendance': {
      id: '/attendance'
      path: '/attendance'
      fullPath: '/attendance'
      preLoaderRoute: typeof AttendanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/schedule/sales': {
      id: '/schedule/sales'
      path: '/sales'
      fullPath: '/schedule/sales'
      preLoaderRoute: typeof ScheduleSalesRouteImport
      parentRoute: typeof ScheduleRoute
    }
    '/schedule/my': {
      id: '/schedule/my'
      path: '/my'
      fullPath: '/schedule/my'
      preLoaderRoute: typeof ScheduleMyRouteImport
      parentRoute: typeof ScheduleRoute
    }
  }
}

interface ScheduleRouteChildren {
  ScheduleMyRoute: typeof ScheduleMyRoute
  ScheduleSalesRoute: typeof ScheduleSalesRoute
}

const ScheduleRouteChildren: ScheduleRouteChildren = {
  ScheduleMyRoute: ScheduleMyRoute,
  ScheduleSalesRoute: ScheduleSalesRoute,
}

const ScheduleRouteWithChildren = ScheduleRoute._addFileChildren(
  ScheduleRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AttendanceRoute: AttendanceRoute,
  CalendarRoute: CalendarRoute,
  CustomHolidaysRoute: CustomHolidaysRoute,
  LeaveRoute: LeaveRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  ReportsRoute: ReportsRoute,
  ScheduleRoute: ScheduleRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
